[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CXPN Admin Guide"
authors = [{name = "jt", email = "jimmy@colfax-intl.com"}]
dynamic = ["version", "description"]
